// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MasterNodeMetaInfoRequest.proto

// Protobuf Java Version: 3.25.1
package org.hiraeth.govern.server.node.master.Request;

public final class MasterNodeMetaInfoRequestProto {
  private MasterNodeMetaInfoRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MasterNodeMetaInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:govern.MasterNodeMetaInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 node_id = 1;</code>
     * @return The nodeId.
     */
    int getNodeId();

    /**
     * <code>bool is_controller_candidate = 2;</code>
     * @return The isControllerCandidate.
     */
    boolean getIsControllerCandidate();
  }
  /**
   * Protobuf type {@code govern.MasterNodeMetaInfoRequest}
   */
  public static final class MasterNodeMetaInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:govern.MasterNodeMetaInfoRequest)
      MasterNodeMetaInfoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MasterNodeMetaInfoRequest.newBuilder() to construct.
    private MasterNodeMetaInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MasterNodeMetaInfoRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MasterNodeMetaInfoRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MasterNodeMetaInfoRequestProto.internal_static_govern_MasterNodeMetaInfoRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MasterNodeMetaInfoRequestProto.internal_static_govern_MasterNodeMetaInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.class, MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.Builder.class);
    }

    public static final int NODE_ID_FIELD_NUMBER = 1;
    private int nodeId_ = 0;
    /**
     * <code>int32 node_id = 1;</code>
     * @return The nodeId.
     */
    @Override
    public int getNodeId() {
      return nodeId_;
    }

    public static final int IS_CONTROLLER_CANDIDATE_FIELD_NUMBER = 2;
    private boolean isControllerCandidate_ = false;
    /**
     * <code>bool is_controller_candidate = 2;</code>
     * @return The isControllerCandidate.
     */
    @Override
    public boolean getIsControllerCandidate() {
      return isControllerCandidate_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeId_ != 0) {
        output.writeInt32(1, nodeId_);
      }
      if (isControllerCandidate_ != false) {
        output.writeBool(2, isControllerCandidate_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nodeId_);
      }
      if (isControllerCandidate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isControllerCandidate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest)) {
        return super.equals(obj);
      }
      MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest other = (MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest) obj;

      if (getNodeId()
          != other.getNodeId()) return false;
      if (getIsControllerCandidate()
          != other.getIsControllerCandidate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId();
      hash = (37 * hash) + IS_CONTROLLER_CANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsControllerCandidate());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code govern.MasterNodeMetaInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:govern.MasterNodeMetaInfoRequest)
        MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MasterNodeMetaInfoRequestProto.internal_static_govern_MasterNodeMetaInfoRequest_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MasterNodeMetaInfoRequestProto.internal_static_govern_MasterNodeMetaInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.class, MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.Builder.class);
      }

      // Construct using MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = 0;
        isControllerCandidate_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MasterNodeMetaInfoRequestProto.internal_static_govern_MasterNodeMetaInfoRequest_descriptor;
      }

      @Override
      public MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest getDefaultInstanceForType() {
        return MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.getDefaultInstance();
      }

      @Override
      public MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest build() {
        MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest buildPartial() {
        MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest result = new MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isControllerCandidate_ = isControllerCandidate_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest) {
          return mergeFrom((MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest other) {
        if (other == MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest.getDefaultInstance()) return this;
        if (other.getNodeId() != 0) {
          setNodeId(other.getNodeId());
        }
        if (other.getIsControllerCandidate() != false) {
          setIsControllerCandidate(other.getIsControllerCandidate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                nodeId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                isControllerCandidate_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int nodeId_ ;
      /**
       * <code>int32 node_id = 1;</code>
       * @return The nodeId.
       */
      @Override
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>int32 node_id = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(int value) {

        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 node_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0;
        onChanged();
        return this;
      }

      private boolean isControllerCandidate_ ;
      /**
       * <code>bool is_controller_candidate = 2;</code>
       * @return The isControllerCandidate.
       */
      @Override
      public boolean getIsControllerCandidate() {
        return isControllerCandidate_;
      }
      /**
       * <code>bool is_controller_candidate = 2;</code>
       * @param value The isControllerCandidate to set.
       * @return This builder for chaining.
       */
      public Builder setIsControllerCandidate(boolean value) {

        isControllerCandidate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_controller_candidate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsControllerCandidate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isControllerCandidate_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:govern.MasterNodeMetaInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:govern.MasterNodeMetaInfoRequest)
    private static final MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest();
    }

    public static MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MasterNodeMetaInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<MasterNodeMetaInfoRequest>() {
      @Override
      public MasterNodeMetaInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MasterNodeMetaInfoRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MasterNodeMetaInfoRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public MasterNodeMetaInfoRequestProto.MasterNodeMetaInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_govern_MasterNodeMetaInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_govern_MasterNodeMetaInfoRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037MasterNodeMetaInfoRequest.proto\022\006gover" +
      "n\"M\n\031MasterNodeMetaInfoRequest\022\017\n\007node_i" +
      "d\030\001 \001(\005\022\037\n\027is_controller_candidate\030\002 \001(\010" +
      "BG\n%com.hiraeth.govern.server.node.maste" +
      "rB\036MasterNodeMetaInfoRequestProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_govern_MasterNodeMetaInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_govern_MasterNodeMetaInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_govern_MasterNodeMetaInfoRequest_descriptor,
        new String[] { "NodeId", "IsControllerCandidate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
